# frontend/Dockerfile

# 1. Use an official Node.js Alpine image for a small, secure base
FROM node:22.20.0-alpine

# 2. Set the working directory
WORKDIR /app

# 3. Copy package.json and package-lock.json FIRST for layer caching
COPY package*.json ./
RUN npm install

# 4. Copy the rest of the application source code
COPY . .

# 5. Expose the port React dev server runs on
EXPOSE 3000

# 6. The command to start the app
CMD ["npm", "run","dev"]