# fly.toml file generated for maher-crosspost-api

app = 'maher-crosspost-api'
primary_region = 'fra' # e.g., 'lax' or 'ams'

# --- THIS IS THE CRITICAL SECTION ---
[build]
  dockerfile = 'backend/Dockerfile' # Explicitly point to the backend's Dockerfile
# ------------------------------------

[env]
  PORT = '80'

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024