"""add content_text and rename content to content_html on posts

Revision ID: 2dca08637545
Revises: 379cf058d836
Create Date: 2025-10-01 16:36:46.547527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dca08637545'
down_revision = '379cf058d836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('content_text', sa.Text(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content_text')
        batch_op.drop_column('content_html')

    # ### end Alembic commands ###
