"""add generate_for_twitter to posts table

Revision ID: f2dec219708b
Revises: 2dca08637545
Create Date: 2025-10-05 20:32:46.599233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2dec219708b'
down_revision = '2dca08637545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generate_for_twitter', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('generate_for_twitter')

    # ### end Alembic commands ###
